import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/page-intro";
import { Leaf, Compass, Hand, Sprout } from "lucide-react";
export const metadata: Metadata = { title: "Outdoor Preschool Program" };
export default function ProgramPage() {
  return <><PageIntro eyebrow="OUR PROGRAM" title={<>A little wild.<br/><em>A lot of learning.</em></>} intro="An outdoor preschool for children ages 2½ to 5, where playful exploration and caring guidance help each child grow." />
    <section className="section-pad content-section"><div className="container split-content"><div><div className="section-label"><span>01</span><span className="label-line"/> THE MORNING, THEIR WAY</div><h2>Curiosity leads.<br/><em>Learning follows.</em></h2></div><div className="prose"><p className="lead">Children learn best when they can touch, try, imagine, and ask their own questions.</p><p>At Mother Nature Academy, children spend their morning outdoors in a natural setting. Educators observe, listen, and offer thoughtful invitations to learn—following a child’s interests while helping build confidence and readiness for what comes next.</p><p>From the nature trail to open-ended building and dramatic play, children can move between experiences at their own pace. A discovery in one moment may become a story, a counting game, or a whole group project the next.</p><p>Our mixed-age community gives children space to learn alongside one another: younger children see new possibilities, while older children practice sharing what they know.</p><Link className="text-link" href="/curriculum">Explore our curriculum <span>↗</span></Link></div></div></section>
    <section className="program-cards"><div className="container program-card-grid"><article><span><Leaf/></span><h3>All morning outdoors</h3><p>Fresh air, open space, and hands-on experiences on a private farm.</p></article><article><span><Compass/></span><h3>Guided by wonder</h3><p>Children’s questions and interests shape meaningful explorations.</p></article><article><span><Hand/></span><h3>Learning through play</h3><p>Building, creating, pretending, and practicing real skills every day.</p></article><article><span><Sprout/></span><h3>Room to become</h3><p>Support for growing independence, relationships, and kindergarten readiness.</p></article></div></section>
    <section className="callout-band"><div className="container callout-inner"><p>Want to see whether our program feels right for your family?</p><Link className="button" href="/register">Ask us a question <span>↗</span></Link></div></section>
  </>;
}
